export const adminRoutes = {
  dashboard: '/admin',
  companies: '/admin/companies',
  companyDetail: '/admin/companies/:id',
  createCompany: '/admin/companies/create',
  sources: '/admin/sources',
  crm: '/admin/crm',
  crmActivities: '/admin/crm/activities',
  invoices: '/admin/invoices',
  tickets: '/admin/support',
  createTicket: '/admin/support/create',
  editTicket: '/admin/support/:nid/edit',
  keyFigures: '/admin/key-figures',
  latestCompanies: '/admin/companies/latest',
  companyEdit: '/admin/companies/:id/edit',
  crmCreate: '/admin/crm/create',
  crmActivityEdit: '/admin/crm/activities/:id/edit',
  books: '/admin/books',
  booksCreate: '/admin/books/create',
  bookEditOrder: '/admin/books/:bid/edit-order',
  handbook: '/admin/handbook',
  handbookTableOfContents: '/admin/handbook/table-of-contents',
  handbookPrint: '/admin/handbook/print',
  handbookPage: '/admin/handbook/pages/:nid',
  handbookPageTab: '/admin/handbook/pages/:nid/:tab',
  handbookPageMeta: '/admin/handbook/pages/:nid/meta',
  // Key Figures renders its sections as tabs on one route (?tab=…), so these are
  // query-string deep links, not separate routes.
  keyFiguresTab: '/admin/key-figures?tab=overview',
  keyFiguresTraffic: '/admin/key-figures?tab=traffic',
  keyFiguresKeywords: '/admin/key-figures?tab=keywords',
  accountDashboard: '/admin/dashboard',
  users: '/admin/users',
  subscriptions: '/admin/subscriptions',
  activity: '/admin/activity',
  analytics: '/admin/analytics',
  settings: '/admin/settings',
  newsletters: '/admin/newsletters',
  newsletterCreate: '/admin/newsletters/create',
  newsletterEdit: '/admin/newsletters/:nid/edit',
  informationList: '/admin/information-list',
  companyInformationList: '/admin/companies/:id/information-list',
} as const;
