export const adminRoutes = {
  dashboard: '/admin',
  companies: '/admin/companies',
  companyDetail: '/admin/companies/:id',
  createCompany: '/admin/companies/create',
  sources: '/admin/sources',
  crm: '/admin/crm',
  invoices: '/admin/invoices',
  tickets: '/admin/support',
  keyFigures: '/admin/key-figures',
  latestCompanies: '/admin/companies/latest',
  companyEdit: '/admin/companies/:id/edit',
  crmCreate: '/admin/crm/create',
  keyFiguresTab: '/admin/key-figures/overview',
  keyFiguresTraffic: '/admin/key-figures/traffic',
  keyFiguresKeywords: '/admin/key-figures/keywords',
  users: '/admin/users',
  subscriptions: '/admin/subscriptions',
  activity: '/admin/activity',
  analytics: '/admin/analytics',
  settings: '/admin/settings',
} as const;
